dist:
  xenial

language:
  cpp

compiler:
  gcc

# Matrix
#       GAP version: | master |  stable-4.10 | stable-4.9 | required |
#--------------------+--------+--------------+------------+----------+
# packages:   master | 64-bit |            - |          - |        - |
# packages:   newest | 64-bit | 64- & 32-bit |          - |        - |
# packages: required | 32-bit |   (coverage) |     64-bit |   64-bit |

# Plus: linting

matrix:
  include:
    - env:
      - SUITE=lint

    - env:
      - SUITE=test
      - GAPBR=master
      - PACKAGES=master
      - ABI=64

    - env:
      - SUITE=test
      - GAPBR=master
      - PACKAGES=newest
      - ABI=64

    - env:
      - SUITE=test
      - GAPBR=master
      - PACKAGES=required
      - ABI=32
      addons:
        apt_packages:
          - g++-multilib

    - env:
      - SUITE=test
      - GAPBR=stable-4.10
      - PACKAGES=newest
      - ABI=32
      addons:
        apt_packages:
          - g++-multilib

    - env:
      - SUITE=test
      - GAPBR=stable-4.10
      - PACKAGES=newest
      - ABI=64

    - env:
      - SUITE=test
      - GAPBR=stable-4.9
      - PACKAGES=required
      - ABI=64

    - env:
      - SUITE=test
      - GAPBR=required
      - PACKAGES=required
      - ABI=64

    - env:
      - SUITE=coverage
      - GAPBR=stable-4.10
      - PACKAGES=required
      - ABI=64
      - THRESHOLD=95

install:
  # GAP requires special flags for compilation in 32-bit mode
  - if [ "$ABI" == "32" ]; then
      export GAP_FLAGS="ABI=32 --host=i686-linux-gnu";
      export PKG_FLAGS="CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32 LOPTS=-m32 --host=i686-linux-gnu";
    fi;

before_script:
  - export GAPROOT="$HOME/gap"
  - scripts/travis-build-dependencies.sh

script:
  - scripts/travis-build-semigroups.sh && scripts/travis-test.sh
