name: Semigroups
version: 4.0.0
date: 2022-02-28
description: |
    A package for semigroups and monoids

authors:
    - name: James Mitchell
      url: https://jdbm.me

maintainers:
    - name: James Mitchell
      url: https://jdbm.me

contributors:
    - name: Stuart Burrell
      url: https://stuartburrell.github.io
    - name: Manuel Delgado
      url: https://cmup.fc.up.pt/cmup/mdelgado/
    - name: James East
      url: https://goo.gl/MuiJu5
    - name: Attila Egri-Nagy
      url: http://www.egri-nagy.hu
    - name: Luke Elliott
      url: https://le27.github.io/Luke-Elliott/
    - name: Nicholas Ham
      url: https://n-ham.github.io
    - name: Max Horn
      url: https://www.quendi.de/math
    - name: Christopher Jefferson
      url: https://caj.host.cs.st-andrews.ac.uk/
    - name: Julius Jonusas
      url: http://julius.jonusas.work
    - name: Dima V. Pasechnik
      url: http://users.ox.ac.uk/~coml0531/
    - name: Markus Pfeiffer
      url: https://www.morphism.de/~markusp/
    - name: Christopher Russell
      url: mailto:cr66@st-andrews.ac.uk
    - name: Benjamin Steinberg
      url: https://bsteinberg.ccny.cuny.edu/Webpage/
    - name: Finn Smith
      url: mailto:fls3@st-andrews.ac.uk
    - name: Jhevon Smith
      url: https://math.sci.ccny.cuny.edu/person/jhevon-smith/
    - name: Maria Tsalakou
      url: https://mariatsalakou.github.io/
    - name: Murray Whyte
      url: mailto:mw231@st-andrews.ac.uk
    - name: Wilf A. Wilson
      url: https://wilf.me
    - name: Michael Young
      url: https://mct25.host.cs.st-andrews.ac.uk

GAP: ">=4.10.0"

needed-pkgs:
    - name: "datastructures"
      version: ">=0.2.5"
      url: "https://gap-packages.github.io/datastructures"
    - name: "digraphs"
      version: ">=1.5.0"
      url: "https://digraphs.github.io/Digraphs"
    - name: "genss"
      version: ">=1.6.5"
      url: "https://gap-packages.github.io/genss"
    - name: "images"
      version: ">=1.3.0"
      url: "https://gap-packages.github.io/images/"
    - name: "IO"
      version: ">=4.5.1"
      url: "https://gap-packages.github.io/io"
    - name: "orb"
      version: ">=4.8.2"
      url: "https://gap-packages.github.io/orb"

suggested-pkgs:
    - name: "GAPDoc"
      version: ">=1.6.3"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "AutoDoc"
      version: ">=2020.08.11"
      url: "https://gap-packages.github.io/AutoDoc"

www: https://semigroups.github.io/Semigroups
readme: README.md
packageinfo: https://semigroups.github.io/Semigroups/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/semigroups/Semigroups/releases/download/v4.0.0/semigroups-4.0.0.tar.gz

abstract: |
    
              The Semigroups package is a GAP package for semigroups, and monoids.
              There are particularly efficient methods for finitely presented
              semigroups and monoids, and for semigroups and monoids consisting of
              transformations, partial permutations, bipartitions, partitioned
              binary relations, subsemigroups of regular Rees 0-matrix semigroups,
              and matrices of various semirings including boolean matrices,
              matrices over finite fields, and certain tropical matrices.
    
              Semigroups contains efficient methods for creating semigroups,
              monoids, and inverse semigroups and monoids, calculating their
              Green's structure, ideals, size, elements, group of units, small
              generating sets, testing membership, finding the inverses of a
              regular element, factorizing elements over the generators, and so on.
              It is possible to test if a semigroup satisfies a particular
              property, such as if it is regular, simple, inverse, completely
              regular, and a large number of further properties.
    
              There are methods for finding presentations for a semigroup, the
              congruences of a semigroup, the maximal subsemigroups of a finite
              semigroup, smaller degree partial permutation representations, and
              the character tables of inverse semigroups. There are functions for
              producing pictures of the Green's structure of a semigroup, and for
              drawing graphical representations of certain types of elements.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
