name: "GAP"
on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    # Every day at 3:15 AM UTC
    - cron: '15 3 * * *'

jobs:
  test:
    name: "GAP ${{ matrix.gap-branch }}"
    runs-on: "${{ matrix.os }}-latest"
    # Don't run this twice for PRs from branches in the same repository
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
        gap-branch:
          - master
          - stable-4.11

        include:
          # GAP stable-4.10
          - gap-branch: stable-4.10
            pkgs-to-clone: "datastructures images digraphs/digraphs"
            os: ubuntu

    steps:
      - uses: actions/checkout@v2
      - name: "Install GAP and clone/compile necessary packages"
        uses: gap-actions/setup-gap@v2
        env:
          # We don't understand why this is necessary. Hopefully it can be
          # removed in the fullness of time.
          LDFLAGS: "-pthread"
        with:
          GAP_PKGS_TO_CLONE: "${{ matrix.pkgs-to-clone }}"
          GAP_PKGS_TO_BUILD: "digraphs genss io orb images datastructures profiling"
          GAPBRANCH: ${{ matrix.gap-branch }}
      - name: "Build Semigroups"
        uses: gap-actions/build-pkg@v1
      - name: "Run tst/teststandard.g"
        uses: gap-actions/run-pkg-tests@v2
        with:
          GAP_TESTFILE: "tst/teststandard.g"
      - uses: gap-actions/process-coverage@v2
      - uses: codecov/codecov-action@v1
