name: "CI"

# Trigger the workflow on push or pull request
on:
  pull_request:
  push:
    branches-ignore:
      - rc-v[0-9]+.[0-9]+.[0-9]+

jobs:
  lint:
    name: "lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install dependencies . . ."
        run: |
          sudo pip install gaplint 
      - name: "Run gaplint . . ."
        run: bash etc/gaplint.sh
  test:
    name: "GAP ${{ matrix.gap-branch }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gap-branch:
          - master
          - stable-4.11

        include:
          - gap-branch: stable-4.10
            pkgs-to-clone: 'datastructures images digraphs/digraphs'

    steps:
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-gap-for-packages@v1
        with:
          GAP_PKGS_TO_CLONE: "${{ matrix.pkgs-to-clone }}"
          GAP_PKGS_TO_BUILD: "digraphs genss io orb images datastructures profiling"
          GAPBRANCH: ${{ matrix.gap-branch }}
      - uses: gap-actions/run-test-for-packages@v1
        with:
          GAP_TESTFILE: "tst/teststandard.g"
