name: "Standard tests"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "master"
      - "stable-*.*"
  schedule:
    # Every day at 3:15 AM UTC
    - cron: '15 3 * * *'

jobs:
  test:
    name: "${{ matrix.gap-branch }} / ${{ matrix.os }} / ${{ matrix.ABI }}-bit"
    runs-on: "${{ matrix.os }}-latest"
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
        gap-branch:
          - master
          - stable-4.12
        ABI:
          - 64
        include:
          # macOS job
          - gap-branch: master
            # to ensure datastructures>= v0.2.6
            pkgs-to-clone: "datastructures"
            os: macos
            ABI: 64

    steps:
      - uses: actions/checkout@v3
      - name: "Install dependencies (macOS only!)"
        if: ${{ runner.os == 'macOS' }}
        run: brew install automake
      # Setup ccache, to speed up repeated compilation of the same binaries
      # (i.e., GAP and the packages)
      - name: "Setup ccache"
        if: ${{ runner.os != 'Windows' }}
        uses: Chocobo1/setup-ccache-action@v1
        with:
          update_packager_index: false
          override_cache_key: ${{ runner.os }}-${{ matrix.gap-branch }}-${{ matrix.ABI }}-${{ github.ref }}
          override_cache_key_fallback: ${{ runner.os }}-${{ matrix.gap-branch }}-${{ matrix.ABI }}
      - name: "Install GAP and clone/compile necessary packages"
        uses: gap-actions/setup-gap@v2
        env:
          # We don't understand why this is necessary. Hopefully it can be
          # removed in the fullness of time.
          LDFLAGS: "-pthread"
        with:
          # digraphs included here to ensure version >=1.5.0
          GAP_PKGS_TO_CLONE: "digraphs/digraphs ${{ matrix.pkgs-to-clone }}"
          GAP_PKGS_TO_BUILD: "digraphs io orb datastructures profiling"
          GAPBRANCH: ${{ matrix.gap-branch }}
          ABI: ${{ matrix.ABI }}
      - name: "Build Semigroups"
        uses: gap-actions/build-pkg@v1
        with:
          ABI: ${{ matrix.ABI }}
          CONFIGFLAGS: --disable-hpcombi
      - name: "Run Semigroups package's tst/teststandard.g"
        uses: gap-actions/run-pkg-tests@v2
      - uses: gap-actions/process-coverage@v2
      - uses: codecov/codecov-action@v2
      - name: "Run GAP's tst/testinstall.g"
        uses: gap-actions/run-pkg-tests@v2
        with:
          GAP_TESTFILE: "ci/run-gap-testinstall.g"
