name: "GAP tests"

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  test:
    name: "GAP ${{ matrix.gap-branch }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        gap-branch:
          - master
          - stable-4.11

    steps:
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-gap-for-packages@v1
        with:
          GAP_PKGS_TO_BUILD: "digraphs genss io orb images datastructures profiling"
          GAPBRANCH: ${{ matrix.gap-branch }}
      - uses: gap-actions/run-test-for-packages@v1
        with:
          GAP_TESTFILE: "tst/teststandard.g"
