name: "Lint"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
      - "stable-*.*"
  schedule:
    # Every day at 3:10 AM UTC
    - cron: '10 3 * * *'

jobs:
  gaplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install dependencies . . ."
        run: sudo pip install gaplint==1.1.3
      - name: "Run gaplint . . ."
        run: bash etc/gaplint.sh

  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install cpplint
      - run: bash etc/cpplint.sh
